### PR TITLE
6.0.0 💥

### LINKED ISSUE #130: Drop support of Node.js 0.10/0.12
Due to [Node LTS schedule](https://github.com/nodejs/LTS/blob/master/schedule.png) - 0.10 version will not be maintained after October 2016 - so we can make 5.x version of `got` last compatible version with 0.10 and drop support in 6.x and above.

### PR DESCRIPTION
**Pull request by floatdrop**
### Overview

`6.0.0` release drops Node.JS 0.10/0.12 support, so now we can replace lots of modules and reduce dependency tree more than twice:

```
got@5.2.0                               got@6.0.0
├─┬ create-error-class@2.0.1            ├─┬ create-error-class@3.0.0
│ ├── capture-stack-trace@1.0.0         │ └── capture-stack-trace@1.0.0
│ └── inherits@2.0.1                    ├── @floatdrop/duplexer2@0.1.4
├─┬ duplexify@3.4.2                     ├── get-stream@1.1.0
│ ├─┬ end-of-stream@1.0.0               ├── is-plain-obj@1.1.0
│ │ └─┬ once@1.3.3                      ├── is-redirect@1.0.0
│ │   └── wrappy@1.0.1                  ├── is-stream@1.0.1
│ └─┬ readable-stream@2.0.4             ├── lowercase-keys@1.0.0
│   ├── core-util-is@1.0.2              ├── node-status-codes@1.0.0
│   ├── inherits@2.0.1                  ├── timed-out@2.0.0
│   ├── isarray@0.0.1                   ├── unzip-response@1.0.0
│   ├── process-nextick-args@1.0.5      └─┬ url-parse-lax@1.0.0
│   ├── string_decoder@0.10.31            └── prepend-http@1.0.3
│   └── util-deprecate@1.0.2
├── is-plain-obj@1.1.0
├── is-redirect@1.0.0
├── is-stream@1.0.1
├── lowercase-keys@1.0.0
├── node-status-codes@1.0.0
├── object-assign@4.0.1
├─┬ parse-json@2.2.0
│ └─┬ error-ex@1.3.0
│   └── is-arrayish@0.2.1
├─┬ pinkie-promise@2.0.0
│ └── pinkie@2.0.1
├─┬ read-all-stream@3.0.1
│ ├─┬ pinkie-promise@1.0.0
│ │ └── pinkie@1.0.0
│ └─┬ readable-stream@2.0.4
│   ├── core-util-is@1.0.2
│   ├── inherits@2.0.1
│   ├── isarray@0.0.1
│   ├── process-nextick-args@1.0.5
│   ├── string_decoder@0.10.31
│   └── util-deprecate@1.0.2
├── timed-out@2.0.0
├── unzip-response@1.0.0
└─┬ url-parse-lax@1.0.0
  └── prepend-http@1.0.3
```

This decreases package size about 3x and improves installation time.

Callback API was dropped and Promises are default way to work with `got` now.

### Important commits

- Replace read-all-stream with get-stream #132 – f0c98438666268e149f2f6272df7ad5936ce99f1
- Drop callback interface #133 – 023b2f1ad17e6c228909fb4ecb4be2d6b6bdb606
- Remove parse-json dependency #134 – 95b4f8ce7186714e16df9ed51dc1a34de8d5dcfb
- Replace duplexify with something #135 – 6da66b7ee801b3d434162f94a288aac55e785172

Closes #130

### CODE REVIEW

**Comment by sindresorhus** [comment]
:+1: Looks really good to me! When do we want to release this?

**Comment by sindresorhus** [comment]
Can you drop the `inherits` dependency from `create-error-class`? Just use normal JS subclassing with Object.create().

Can you do a scoped package `@floatdrop/duplexer2` for https://github.com/floatdrop/duplexer2/commit/f770b342321823b20bcf86177961178ac619be69 ? I don't want us to depend on a git repo.

**Comment by floatdrop** [comment]
> Looks really good to me! When do we want to release this?

Thanks!  I'm thinking about `rc` version to test changes, but have no idea when to publish major.

**Comment by sindresorhus** [comment]
> Thanks! I'm thinking about rc version to test changes

:+1: https://docs.npmjs.com/cli/dist-tag

**Comment by sindresorhus** [comment]
Yay! \o/

Super nice work on all this @floatdrop :)

celebration

**Comment by kevva** [comment]
:star:

Great job!

**Comment by floatdrop** [comment]
a9peaa1_460sv mp4

**Comment by maxvipon** [comment]
:fire:

**Pull request merged**
