### PR TITLE
Gracefully handle invalid `Location` redirect URLs

### LINKED ISSUE #604: UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL
As per below example domain redirects `302` to invalid host name empty `http://` this breaks `got` and throws `UnhandledPromiseRejectionWarning` regardless of any attempt to `catch` errors.

```js
const got = require('got');

(async () => {
    try {
        const response = await got('fashion-bcom-prod.herokuapp.com');
        console.log(response.body);
    } catch (error) {
        console.log(error.response.body);
    }
})();
```

```bash
Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> { TypeError [ERR_INVALID_URL]: Invalid URL: //
    at onParseError (internal/url.js:219:17)
    at parse (internal/url.js:228:3)
    at new URL (internal/url.js:311:5)
    at cacheableRequest (/wvp/node_modules/got/source/request-as-event-emitter.js:123:20)
    at ClientRequest.handler (/wvp/node_modules/cacheable-request/src/index.js:118:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at ClientRequest.origin.emit.args [as emit] (/wvp/node_modules/@szmarczak/http-timer/source/index.js:36:11)
    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21) input: '//' } }  reason:  { TypeError [ERR_INVALID_URL]: Invalid URL: //
    at onParseError (internal/url.js:219:17)
    at parse (internal/url.js:228:3)
    at new URL (internal/url.js:311:5)
    at cacheableRequest (/wvp/node_modules/got/source/request-as-event-emitter.js:123:20)
    at ClientRequest.handler (/wvp/node_modules/cacheable-request/src/index.js:118:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at ClientRequest.origin.emit.args [as emit] (/wvp/node_modules/@szmarczak/http-timer/source/index.js:36:11)
    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21) input: '//' }
```

### PR DESCRIPTION
**Pull request by brandon93s**
- Move `new URL` into existing `try...catch` block to gracefully handle failures
- Add test for `ERR_INVALID_URL`

h/t to @alextes for his initial research. 

---
Closes #604

### CODE REVIEW

**Comment by alextes** [comment]
Nice work Brandon93. Lots of little improvements over what I wrote too. Unfortunately it does still suffer from the issue I flagged with the test. This test, like mine, is half functional. It lights up green beautifully, but imagine someone refactors and moves the `new URL` line out of the try/catch , the test won't show up red 😥 . It'll hang ava indefinitely which is something, but if possible I'd like the test red.

Let's see if the other maintainers have an idea of how to fix it, if not, let's merge this and open an issue.

To reproduce, one can copy your test or you could:
```sh
git reset HEAD~
git stash push source
npx ava test/redirects.js
```

**Comment by szmarczak** [comment]
> To reproduce try moving the line back out of the try/catch construct.

So don't move that. :>

**Comment by alextes** [comment]
🙈

**Comment by brandon93s** [comment]
See https://github.com/avajs/ava/issues/1931 for related issue.

**Pull request merged**
