### PR TITLE
feat: add docs for proxy-pass

### PR DESCRIPTION
**Pull request by jarqvi**
#### Checklist

- [x] I have read the documentation.
- [x] I have included a pull request description of my changes.
- [x] I have included some tests.
- [x] If it's a new feature, I have included documentation updates in both the README and the types.

### CODE REVIEW

**Comment by jarqvi** [comment]
Hello!
I recently found myself in need of a specific code but couldn't locate a comprehensive solution. Following an examination of the documentation and conducting several tests, I reached the following conclusion.

As a result, I decided it would be beneficial to submit a pull request (PR) for this, along with an illustrative example, to assist others in utilizing it.

**Comment by sindresorhus** [comment]
I appreciate the pull request, but I feel like documenting Express usage is a bit outside of what we should document in Got. I suggest writing a blog post about it on your blog instead 👍

**Comment by jarqvi** [comment]
Hi!
Thanks.
What do you think if I provide an example in a PR using my HTTP built-in module? Honestly, I don't have a blog, but I really wanted to share this and thought it might be helpful with documentation updates. 🙂

**Comment by sindresorhus** [comment]
I'm still going to pass. More docs means more for us to maintain too. Non-essential docs are better done in community blogs.

You could for example share it here: https://dev.to

**Comment by jarqvi** [comment]
ok, thanks.

**Pull request closed without merging**
