### PR TITLE
Ensure cancel tests wait for a connection before cancelling

### PR DESCRIPTION
**Pull request by lukechilds**
Resolves https://github.com/sindresorhus/got/issues/392

This is just a WIP to explain my findings, don't merge.

**Update:** Ready to merge

Intermittent test failures were caused by cancel tests relying on `setTimeout` to wait for the connection to be established. Resolved by implementing a `connection` event which is still reliable in slow CI environments.

### CODE REVIEW

**Comment by lukechilds** [comment]
@sindresorhus Ok, I think I might know what's causing the cancel test to intermittently fail.

I think it's because on Travis (with AVA concurrency at 4 but only one thread available) any extra async code introduces significant overhead. Because the thread is tied up with four processes, simply calling `Promise.resolve(value).then(fn)` means `fn` has to wait until the thread is free again which could be a while. In most production environments this would take milliseconds but in our specific CI environment this could potentially be in the hundreds of milliseconds due to the thread being overworked.

I think possibly the extra overhead of the Promises introduced in the cache option code is enough to (sometimes) break the cancel tests because they [rely on](https://github.com/sindresorhus/got/blob/883e40f55fed24490c705ff1086ae38c1ce74d2d/test/cancel.js#L40-L44) a `setTimeout(fn, 100)` for the stream to be established before cancelling it.

This is supported by the fact that increasing to `setTimeout(fn, 500)` means that the tests consistently pass. I've re-ran the [Travis build](https://travis-ci.org/lukechilds/got/builds/302318728) about 30 times and tests passed every time.

With `setTimeout(fn, 100)` roughly every 1 in 5 Travis builds failed.

I'm not 100% sure this is the reason why but it seems to make sense. Hopefully the commit messages help you understand how I reached this conclusion.

What are your thoughts?

**Comment by lukechilds** [comment]
Also, for whatever reason, the Travis builds don't seem to be showing up for every commit in this PR. You can view the identical PR on my repo for all the commit builds: https://github.com/lukechilds/got/pull/1

**Comment by lukechilds** [comment]
> Sorry for writing a flaky test 🙈.

Haha, it's a pretty odd edge case, I'm still not 100% sure that's the reason.

> You could consider returning a connection event emitter from the abort server too if it turns flaky again.

I like this solution, if that works we can be pretty sure the problem won't come back again. I'll give it a bash now.

**Comment by lukechilds** [comment]
Ok, so ensuring we reliably wait for the connection via triggering an event as opposed to setTimeout definitely seems to work.

 Just ran the [Travis Build](https://travis-ci.org/lukechilds/got/builds/302372583) another 30 times without a any test failures.



I think this can be merged.

**Comment by sindresorhus** [comment]
Great!

**Comment by AlexTes** [comment]
👏

**Pull request merged**
