### PR TITLE
#606 fix hooks merging inside create

### PR DESCRIPTION
**Pull request by dmitry-vakhnenko**
#606

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you add a test?

**Comment by dmitry-vakhnenko** [comment]
Never write tests before. So, i try.

**Comment by szmarczak** [comment]
This is nonsense.

`got` calls `normalizeArguments`, where options are merged.

https://github.com/sindresorhus/got/blob/7ae6939f920d1174b181063ce61056a8a6def4bc/source/create.js#L33

https://github.com/sindresorhus/got/blob/7ae6939f920d1174b181063ce61056a8a6def4bc/source/normalize-arguments.js#L58

**Comment by szmarczak** [comment]
See #608

**Pull request closed without merging**
