### PR TITLE
Do not use deprecated `request.abort()`

### LINKED ISSUE #1216: Responses are not cached on Node.js ≥ v14.0.0
```
  5 tests failed
  2 known failures
  1 test skipped

  arguments.ts › throws an error when legacy URL is passed
  pagination.ts › pagiantion using searchParams

  cache.ts › cacheable responses are cached


  Difference:

  - 0
  + 1

  › dist/test/cache.js:31:7
  › dist/test/helpers/with-server.js:38:9



  cache.ts › cached response is re-encoded to current encoding option


  Difference:

  - 0
  + 1

  › dist/test/cache.js:42:7
  › dist/test/helpers/with-server.js:38:9



  cache.ts › redirects are cached and re-used internally


  Difference:

  - 2
  + 3

  › dist/test/cache.js:72:7
  › dist/test/helpers/with-server.js:38:9



  cache.ts › can replace the instance's HTTP cache


  Difference:

  - 0
  + 1

  › dist/test/cache.js:215:7
  › dist/test/helpers/with-server.js:38:9



  cache.ts › `isFromCache` stream property is true if the response was cached


  Difference:

  - false
  + true

  › dist/test/cache.js:148:7
  › runMicrotasks (<anonymous>)
  › dist/test/helpers/with-server.js:38:9
```

### PR DESCRIPTION
**Pull request by Giotino**
#### Checklist

- [x] I have read the documentation.
- [x] I have included some tests.

Fixes #1216

### CODE REVIEW

**Comment by szmarczak** [comment]
The tests are still failing:

```
  cache.ts › cacheable responses are cached


  Difference:

  - 0
  + 1

  › dist/test/cache.js:31:7
  › dist/test/helpers/with-server.js:38:9



  cache.ts › cached response is re-encoded to current encoding option


  Difference:

  - 0
  + 1

  › dist/test/cache.js:42:7
  › dist/test/helpers/with-server.js:38:9



  cache.ts › `isFromCache` stream property is true if the response was cached


  Difference:

  - false
  + true

  › dist/test/cache.js:148:7
  › dist/test/helpers/with-server.js:38:9



  cache.ts › redirects are cached and re-used internally


  Difference:

  - 2
  + 3

  › dist/test/cache.js:72:7
  › dist/test/helpers/with-server.js:38:9



  cache.ts › can replace the instance's HTTP cache


  Difference:

  - 0
  + 1

  › dist/test/cache.js:215:7
  › dist/test/helpers/with-server.js:38:9
```

**Comment by szmarczak** [comment]
The `.aborted` getter is still invalid, but lemme fix it :)

**Comment by Giotino** [comment]
> ~The tests are still failing~ sorry forgot to `npm run build`

Yeah, I missed the stream test, I was fixing them.
I also added a build on TravisCI with Node.JS 14, since the related issue was version related.

**Comment by szmarczak** [comment]
I noticed a bug.

```js
z = require('.').stream('https://example.com');
z.resume();
z.once('end', () => { console.log('end'); });
// If you wait for the `end` event, then console.log(z.aborted) it will give you `true`
// That's because the this[kResponse].complete is false for some reason
```

But that doesn't happen with the native Node.js module only:

```js
require('https').get('https://example.com', response => { response.resume(); response
.once('end', () => { console.log(response.complete); }); })
```

**Comment by szmarczak** [comment]
Fortunately I'm about to fix it

**Comment by szmarczak** [comment]
Unfortunately it's harder than it seems :sweat_smile:

**Comment by szmarczak** [comment]
At least I know that it's caused somehow by `decompress-response`...

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/mimic-response/issues/5

**Comment by szmarczak** [comment]
Tests pass on Node.js 14, but fail on 10, 12 and 13. I'll fix this now.

**Comment by szmarczak** [comment]
https://github.com/nodejs/node/issues/33335

**Comment by szmarczak** [comment]
https://github.com/nodejs/node/issues/33336

**Comment by szmarczak** [comment]
Thanks! :raised_hands: Nice work.

**Pull request merged**
