### PR TITLE
Prevent URL pollution

### LINKED ISSUE #1235: got 11.x strips username and password from WHATWG URLs
#### Describe the bug

 - Node.js version: 12.16, 14.2.0
 - OS & version: Debian 10

The code in question is here: https://github.com/sindresorhus/got/blob/50ef99a9856ccd37a75b42f94d023a491728a92d/source/core/index.ts#L656-L658

#### Actual behavior

Got sends an unauthenticated request when credentials are specified within the URL.

#### Expected behavior

`normalizeArguments` should use the `username` and `password` options passed in the `url` parameter given that it's a WHATWG URL and that they are set. This was supported in got 10.x.

#### Code to reproduce

```js
const url = new URL('http://user:pass@localhost:3000');
console.log(url);
got.post(url, {});
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

### PR DESCRIPTION
**Pull request by Giotino**
#### Checklist

- [x] I have read the documentation.
- [x] I have included a pull request description of my changes.
- [x] I have included some tests.

Keeping in mind that
> Properties from options will override properties in the parsed url.

URL's `username` ans `password` are overwritten only if they're not empty (or null) in options.

I'm going to add some tests.

Fixes #1235

### CODE REVIEW

**Comment by Giotino** [comment]
Added some tests

**Comment by Giotino** [comment]
There's no documentation about if `username` and `password` should be replaced (or merged) together or separately.

There's a test `response contains got options` which fails when the `username` and `password` are not replaced together.
The problem is that the URL (only if an object, not a string) from the given `ExtendedGot` is modified by each call and, as it's an object (reference), it's the same object for each call.

Is this an expected behavior? If not the URL should be deep-copied on each call to prevent pollution.

https://github.com/sindresorhus/got/blob/master/source/core/index.ts#L583

Is only a 1 level deep copy, url is copied as a reference that is not enough.

My suggestion is to add
```
if (is.urlInstance(url)) {
  options.url = {...url} as any;
} else {
  options.url = url;
}
```
after line 587

**Comment by szmarczak** [comment]
> There's no documentation about if username and password should be replaced (or merged) together or separately.

Seperately. E.g. a user can have an empty password.

**Comment by szmarczak** [comment]
> If not the URL should be deep-copied on each call to prevent pollution.

Not exactly object copy, but `new URL(url)`.

**Comment by szmarczak** [comment]
This also needs a separate test.

**Comment by Giotino** [comment]
> > If not the URL should be deep-copied on each call to prevent pollution.
> 
> Not exactly object copy, but `new URL(url)`.

Yes, I'm doing it

**Comment by Giotino** [comment]
Check this last commit

**Comment by szmarczak** [comment]
Hint: `git pull origin master --rebase`. So you don't need to commit the `Merge branch 'master' into ...`.

**Comment by szmarczak** [comment]
This just needs a separate test to check against the pollution and we're good to go! :)

**Comment by Giotino** [comment]
> Hint: `git pull origin master --rebase`. So you don't need to commit the `Merge branch 'master' into ...`.

Let's say i need to get used to git... :)

**Comment by szmarczak** [comment]
> Let's say I need to get used to git... :)

I've been there too ;)

> BTW, I added a test, it's like the one which was failing, but simpler

Let me see it.

**Comment by szmarczak** [comment]
Good job! Thanks :raised_hands:

**Pull request merged**
