### PR TITLE
Fix Retry List

### PR DESCRIPTION
**Pull request by MarkHerhold**
The README states that 500 errors are retried but the code does not have this error code. Fix by removing from README.

### CODE REVIEW

**Comment by szmarczak** [comment]
It does.

https://github.com/sindresorhus/got/blob/ca2675e3e5c9db97015e827ce652493a8f9cc1f3/source/index.js#L17-L24

**Comment by MarkHerhold** [comment]
Ah, my apologies. I was staring at the README from master while using got v9.0.0.

**Comment by szmarczak** [comment]
Sure, good point. Many people find this confusing.

@sindresorhus Maybe we should point users to a last release branch by default?

**Comment by sindresorhus** [comment]
@szmarczak Nah. Most projects on GitHub use master as the default branch and development branch. For the latest version, users should visit the npm package or the readme in the relevant Git tag. This is expected knowledge.

**Comment by MarkHerhold** [comment]
I agree with @sindresorhus. Just made a novice mistake. Thanks!

**Pull request closed without merging**
