### PR TITLE
[WIP] Use create-test-server in tests

### PR DESCRIPTION
**Pull request by lukechilds**
Totally forgot about this.

Requested on Gitter:

> @lukechilds We should use https://github.com/lukechilds/create-test-server in the Got tests.

https://gitter.im/got-dev/Lobby?at=59319ef6cf9c13503c4931eb

WIP, not ready to be merged yet.

### CODE REVIEW

**Comment by lukechilds** [comment]
Ok, all good.

Same functionality as before with 190 fewer lines of code.

Also, can anybody explain what [`test/helpers.js`](https://github.com/lukechilds/got/blob/master/test/helpers.js) is testing? Looks like it may be an old test file that's now redundant. Is it ok to delete this?

**Comment by sindresorhus** [comment]
> Also, can anybody explain what test/helpers.js is testing? It's unclear to me, it looks like it could be tidied up a bit though.

See: https://github.com/lukechilds/got/commit/718bacdd3fddf736d6e5e0e71460ec5209325f3a#diff-8cdd6af9921d65cb55c40e628e46afcc Looks like it's just testing that `got.get()` works too, which is what `got()` is aliased to.

**Comment by lukechilds** [comment]
Ahh, ok. All the other test files are pretty self explanatory, this one isn't IMO, especially in master where a few other bits have creeped in and the test name isn't that relevant.

While I'm working on this PR do you want me to clean it up a bit? Maybe also add tests for `got.post`, `got.put`, `got.patch`, `got.head` and `got.delete`?

**Comment by sindresorhus** [comment]
> While I'm working on this PR do you want me to clean it up a bit? Maybe also add tests for got.post, got.put, got.patch, got.head and got.delete?

Sure, that would be great.

**Comment by sindresorhus** [comment]
@lukechilds Do you think you'll ever finish this or should I close? Happy to keep it open if you think you will at some point.

**Comment by sindresorhus** [comment]
Closing this for now. We can reopen later on.

**Comment by lukechilds** [comment]
Just FYI, I still fully intend to finish this, I just haven't because life.

But yeah, no point keeping it open for now 👍

**Comment by szmarczak** [comment]
I can help you :fire:

**Comment by szmarczak** [comment]
Lots of things is gonna change soon, so I see no sense of doing it right now. Tests need to be rewritten anyway. I've got an idea: add some new hooks, so we don't have to implement `EventEmitter` to listen for `connection`, `abort` events etc.

**Comment by sindresorhus** [comment]
Closing as this would have to be done from scratch anyway and it's not a priority right now, the current tests are working fine.

**Pull request closed without merging**
