### PR TITLE
Add 'br' encoding

### PR DESCRIPTION
**Pull request by silverwind**
Noticed that the greatest encoding out there was missing from this list.

### CODE REVIEW

**Comment by silverwind** [comment]
Also, according to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding, there's a possibilty for `compress` encoding, but I don't think this is worth adding here.

**Comment by kevva** [comment]
Is it worth adding a test for this maybe?

**Comment by silverwind** [comment]
That would add a devDep on https://github.com/mayhemydg/iltorb, which requires a native module. I don't think it's worth that as gzip is already tested.

**Comment by kevva** [comment]
How do we decompress the `br` content? Seems like `zlib` [doesn't](https://nodejs.org/api/zlib.html#zlib_class_zlib_unzip).

**Comment by silverwind** [comment]
> How do we decompress the br content?

iltorb can both compress and decompress.

**Comment by kevva** [comment]
Yeah, but I mean when using `got` and you try to fetch `br` encoded content, it wouldn't be decompressed if `decompress` is `true`?

**Comment by silverwind** [comment]
Oh, right. Looks like https://github.com/sindresorhus/decompress-response is lacking support for `br`. I guess it should be added there first.

**Comment by kevva** [comment]
The module I linked further up should handle it without native deps I think, https://github.com/devongovett/brotli.js.

**Comment by silverwind** [comment]
Haven't seen that one yet, but iltorb is well maintained and I haven't had any issues with it yet, even under Windows. Brotli compression is very CPU intensive, so I'd definitely compare the performance before choosing a module.

**Comment by kevva** [comment]
Yup, I'll work on a PR, but I'm willing to sacrifice performance over native deps tbh depending on the impact.

**Comment by silverwind** [comment]
Opened https://github.com/sindresorhus/decompress-response/issues/12 which blocks this issue.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/decompress-response/pull/13#issuecomment-331626197

**Comment by sindresorhus** [comment]
Node.js issue about adding it natively: https://github.com/nodejs/node/issues/18964

**Pull request closed without merging**
