### PR TITLE
Provide timings

### LINKED ISSUE #557: Add ability to time requests
Add ability to capture timings of every HTTP request state, e.g.

> - `time` - if `true`, the request-response cycle (including all redirects) is timed at millisecond resolution. When set, the following properties are added to the response object:
>   - `elapsedTime` Duration of the entire request/response in milliseconds (*deprecated*).
>   - `responseStartTime` Timestamp when the response began (in Unix Epoch milliseconds) (*deprecated*).
>   - `timingStart` Timestamp of the start of the request (in Unix Epoch milliseconds).
>   - `timings` Contains event timestamps in millisecond resolution relative to `timingStart`. If there were redirects, the properties reflect the timings of the final request in the redirect chain:
>     - `socket` Relative timestamp when the [`http`](https://nodejs.org/api/http.html#http_event_socket) module's `socket` event fires. This happens when the socket is assigned to the request.
>     - `lookup` Relative timestamp when the [`net`](https://nodejs.org/api/net.html#net_event_lookup) module's `lookup` event fires. This happens when the DNS has been resolved.
>     - `connect`: Relative timestamp when the [`net`](https://nodejs.org/api/net.html#net_event_connect) module's `connect` event fires. This happens when the server acknowledges the TCP connection.
>     - `response`: Relative timestamp when the [`http`](https://nodejs.org/api/http.html#http_event_response) module's `response` event fires. This happens when the first bytes are received from the server.
>     - `end`: Relative timestamp when the last bytes of the response are received.
>   - `timingPhases` Contains the durations of each request phase. If there were redirects, the properties reflect the timings of the final request in the redirect chain:
>     - `wait`: Duration of socket initialization (`timings.socket`)
>     - `dns`: Duration of DNS lookup (`timings.lookup` - `timings.socket`)
>     - `tcp`: Duration of TCP connection (`timings.connect` - `timings.socket`)
>     - `firstByte`: Duration of HTTP server response (`timings.response` - `timings.connect`)
>     - `download`: Duration of HTTP download (`timings.end` - `timings.response`)
>     - `total`: Duration entire HTTP round-trip (`timings.end`)

– https://github.com/request/request

### PR DESCRIPTION
**Pull request by szmarczak**
Fixes #557

### CODE REVIEW

**Comment by sindresorhus** [comment]
Awesome! Can you add some docs?

**Comment by szmarczak** [comment]
> How accurate is the start time? It's set automatically when timer is invoked. How close is this to when the request truly starts?

I think 0~1ms

> Should this be opt-in? The overhead seems pretty minimal, so maybe keeping it simple and always running is OK.

I agree.

**Comment by sindresorhus** [comment]
> Sure, but please check out #592 first :)

Done

**Comment by szmarczak** [comment]
IDK why but after `git pull --rebase && git add . && git commit -m 'message'` some commits got duplicated (from 7eeb352 to a4d0c47)

**Pull request merged**
