### PR TITLE
parse json based on content-type

### PR DESCRIPTION
**Pull request by Autarc**
Automatic content negotiation if the header is set (prevents missing the `json` option).

### CODE REVIEW

**Comment by floatdrop** [comment]
[`json`](https://github.com/sindresorhus/got#json) is intentionally non-conditional – some servers will not send `application/json` content-type even if they respond in JSON. If option is set to `true` it should always parse body.

**Comment by Autarc** [comment]
Sure it shouldn't replace the existing option but just extend it for convenience. If someone expects the response of a request to be JSON because its mentioned in a documentation, it shouldn't be necessary to manually set it as the server already provides the hint.

**Comment by sindresorhus** [comment]
@floatdrop Most servers are compliant, though, and it would be nice not having to set the JSON option for those. Maybe we should think of the JSON option as an override in the edge-case of the server being non-compliant?

**Comment by julien-f** [comment]
I tend to agree with @floatdrop because getting an object when not expecting one is not very nice :)

Although an explicit option (`jon: 'auto'`) could do.

**Comment by SamVerschueren** [comment]
But then it should be possible to set `json` to `false` in order to not parse it, even if the `Content-Type` is `application/json`. With the current implementation, that is not possible.

**Comment by sindresorhus** [comment]
@SamVerschueren Yup

**Comment by floatdrop** [comment]
> Most servers are compliant, though, and it would be nice not having to set the JSON option for those.

@sindresorhus yes, but if server changes behaviour (or something with proxy in front of it) – worst case scenario is that header and content will change. `got` will get you plain string object and (depends on your code) it can be silently processed (strings have props, right?). In current case you will get `ParseError` immediately.

@SamVerschueren this is possible (or I don't see something), but this is major change.

**Comment by SamVerschueren** [comment]
If `opts.json` is `false` but the content type is `application/json`, the statement still resolves to true.

**Comment by sindresorhus** [comment]
@floatdrop That's true, but if the server sends `application/json`, I think we should trust the server. The whole point of content-type's is that server can indicate what it supports. If it suddenly changes behavior it can break a lot of other things regardless of this change.

**Comment by floatdrop** [comment]
After some time thinking – I'm sure, that automatic negation is not useful. Heres why:

When I want to get parsed data from endpoint I must do two things – ensure, that endpoint is returning json (almost always this easy to see in docs) and ensure, that `content-type` header is in place. With strict options I can skip last part and just type `json: true`.

Also I must worry about `404`/`503` pages, which almost _never_ contains json and spit HTML on to you (with `text/html` content-type of course). This leads not to ParseError, but to very strange behaviours.

May be we can figure out how to solve these issues and get automatic negation about content (`json: 'auto'` maybe as stated above). But this solution should be improved.

**Pull request closed without merging**
