### PR TITLE
Add `pagination.stackAllItems` option

### LINKED ISSUE #1200: Add an option to disable stacking paginated items
#### What problem are you trying to solve?

Use `.paginate()` over huge set of data without fear of memory exhaustion.

#### Describe the feature

When using `.paginate()` over a large/huge set of data, the `allItems` parameter will grow and eat up all memory. Personally, I have no use cases where `currentItems` less `allItems` variables are useful.

In addition to the memory usage issue, the aggregation of `allItems` can cause CPU consumption to grow exponentially (at least with got@10.x.)

Hence the request for a goldfish/dumb/forgetful mode for `.paginate()`

I would go as far as suggesting this to be the default mode (but you surely have a better knowledge of the overall user base needs)

One obvious issue I can forsee is of course the signature of `.pagination` callback functions which currently looks like `(response, allItems, currentItems) => {...}` for the second parameter becomes literaly unusable while the third (`currentItems`) is still possibly useful to some.

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

### PR DESCRIPTION
**Pull request by szmarczak**
Moved from #1204
Fixes #1200

Had to open this PR because git was complaining that the @PopGoesTheWza branch was in middle of merging even though it clearly was not. Dunno what happend.

/cc @PopGoesTheWza

### CODE REVIEW

**Comment by PopGoesTheWza** [comment]
@szmarczak the fuss with previous PR is likely due to me wrongfully pull from `upstream/master` two days ago

**Comment by PopGoesTheWza** [comment]
@sindresorhus @szmarczak I would humbly suggest the following 2 breaking changes:

- Switch order of `allItems` and `currentItems` parameters
- Default value for `stackAllItem` to `false`

My reasoning about parameters order is that (hopefully/probably) most use cases don't need the `allItems` parameters, with `currentItems` typically being more used. As per the default, the computation of `allItems` when unused implies a waste of CPU and RAM resources (and a crash in worst case scenarios)

Anyhow, let me know if/how I can assist more on this PR.

Regards,

**Comment by sindresorhus** [comment]
We cannot do breaking changes for a while, but open a new issue and we’ll consider it for the next major release.

**Comment by PopGoesTheWza** [comment]
Sure. I will open an enhancement request after `stackAllItems` option is released.

**Comment by szmarczak** [comment]
> Switch order of allItems and currentItems parameters

I don't think there's a need to. It doesn't change how the code works.

> Default value for stackAllItem to false

I don't have a particular opinion on this one. I'm good with either.

**Pull request merged**
