### PR TITLE
Fix error handling for errors thrown from http

### PR DESCRIPTION
**Pull request by jotto**
<details>
<summary>Error: "value" required in setHeader("user-agent", value)</summary>

```
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:354:11)
    at new ClientRequest (_http_client.js:86:14)
    at Object.exports.request (http.js:31:10)
    at get (./node_modules/got/index.js:49:18)
    at Immediate.setImmediate (./node_modules/got/index.js:124:3)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```
</details>

#### To reproduce:

```javascript
const got = require("got");
got("http://example.com", { headers: { "user-agent": undefined } }).catch(err =>
  console.log("caught err", err)
);


```

### CODE REVIEW

**Comment by jotto** [comment]
https://github.com/sindresorhus/got/pull/364/files?w=1

**Comment by jotto** [comment]
I'm so far unable to reproduce this from the `got` repo itself (hence no tests), but when running from a separate directory where `got` is a dependency - the snippet from the description can reproduce it.

**Comment by sindresorhus** [comment]
> but when running from a separate directory where got is a dependency

Are you running `master` version of Got from that directory?

Errors should already be handled by: https://github.com/sindresorhus/got/blob/8b040afc0749523fcaaf6db81702c27e74f7a1d2/index.js#L258-L260

**Comment by jotto** [comment]
> Are you running master version of Got from that directory?

```bash
mkdir got-test
cd got-test
yarn add got
```

which results in a package.json of:

```json
{
  "dependencies": {
    "got": "^7.1.0"
  }
}
```

**Comment by AlexTes** [comment]
@jotto Sindre is saying the code in master already handles the issue you're describing 😄 . You can't reproduce it because the issue is fixed in master.
He's linking code currently in master (8b040af), not yet released, you're pointing at the code of the installed version 7.1.0 (b725ef5). You can find that code in your `node_modules` dir or alternatively [here](https://github.com/sindresorhus/got/blob/b725ef576864fc6dd331b4df58ddb12f2f7d6b3a/index.js), which I got by going to 'Code' -> 'releases' -> 'v7.1.0'.

**Comment by jotto** [comment]
oh, I see now. Thank you @AlexTes! Sorry for the misunderstanding.

So may I gently ask for a release of master?

**Comment by sindresorhus** [comment]
Yes, I'm planning a new release very soon. I just didn't want to do one yet as I've been busy and wouldn't have had time to deal with potential issues the new version.

**Comment by jotto** [comment]
> Yes, I'm planning a new release very soon. I just didn't want to do one yet as I've been busy and wouldn't have had time to deal with potential issues the new version.

_very_ gentle bump/ping

**Pull request closed without merging**
