### PR TITLE
feat: `pagination` parameters as object

### LINKED ISSUE #1215: Changes to the `.pagination` API
#### What problem are you trying to solve?

Improve `.pagination` API (and possibly performance and stability)

#### Describe the feature

I would humbly suggest the following 2 breaking changes:

- Switch order of `allItems` and `currentItems` parameters of `pagination.paginate`, `pagination.filter` and `pagination.shouldContinue`

My reasoning about parameters order is that probably most use cases don't need the `allItems` parameters, with `currentItems` typically being more used. To be confirmed by other users, but if indeed `currentItems` is used more than `allItems` then it should reflect in the order of parameters.

It doesn't change how the Got code works but could save custom `pagination.paginate`, `pagination.filter` and `pagination.shouldContinue` from having an unused and unaesthetic `_` as the second parameter... ;)

- Default value for `stackAllItem` to `false`

As per the default of `allItems`, it implies a waste of CPU and RAM resources when unused. This is especially noticeable when iterating large datasets (and can results in a node.js crash in worst case scenarios)

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

### PR DESCRIPTION
**Pull request by PopGoesTheWza**
BREAKING CHANGE

Fixes #1215 

#### Checklist

- [x] I have read the documentation.
- [ ] I have included a pull request description of my changes.
- [ ] I have included some tests.
- [ ] If it's a new feature, I have included documentation updates in both the README and the types.

### CODE REVIEW

**Comment by PopGoesTheWza** [comment]
@szmarczak should I close this PR?

**Comment by szmarczak** [comment]
Well I don't mind if yours gets merged instead :) @sindresorhus

**Comment by sindresorhus** [comment]
I went with #1644 as it was technically first (that's usually how I resolve duplicate PRs that are the same quality).

Sorry for the wasted work @PopGoesTheWza. It was unfortunate that the timing was so so close.

If you see any improvements to https://github.com/sindresorhus/got/pull/1644 or the pagination code in general, we're more than happy to other PRs from you 🙌🏻

**Comment by PopGoesTheWza** [comment]
> Sorry for the wasted work @PopGoesTheWza. It was unfortunate that the timing was so so close.

No worries. It offered me the possibility to criticize @szmarczak work! ;)

**Comment by sindresorhus** [comment]
> It offered me the possibility to criticize @szmarczak work! ;)

PR reviews are the best kind of contribution, by the way. 👍🏻

**Pull request closed without merging**
