### PR TITLE
Use make-error instead of create-error-class (see #176).

### PR DESCRIPTION
**Pull request by julien-f**
If you think it's worth it, I am not trying to impose my lib :laughing:

### CODE REVIEW

**Comment by sindresorhus** [comment]
@floatdrop Is this something you still want?

**Comment by floatdrop** [comment]
@sindresorhus I don't know, they quite same to me.

**Comment by sindresorhus** [comment]
@julien-f Would there be any actual benefits of switching?

**Comment by julien-f** [comment]
@sindresorhus Nope, no benefits other than avoiding a duplicate library :)

By the way, I am getting fed up with abandoned repos were the maintainers (and often only npm owner) do not answer anymore so I created a GitHub organization (@JsCommunity) to avoid this kind of issues. Any opinion on this? (This might not be the best place to discuss about this, feel free to open [an issue there](https://github.com/JsCommunity/jscommunity.github.io/issues/new)).

**Comment by sindresorhus** [comment]
Ok, then I don't really see the point of switching.

-

> Any opinion on this? (This might not be the best place to discuss about this, feel free to open an issue there).

Can you open an issue there called `Feedback` and mention me?

**Comment by sindresorhus** [comment]
@floatdrop Now that we target Node.js 4, wouldn't it be better to actually subclass the errors?

For example:

```js
class HttpError extends Error {
	constructor(message) {
		super(message);
		this.name = this.constructor.name;
		this.message = 'Unicorns';
	}
}
```

**Comment by floatdrop** [comment]
@sindresorhus to be honest, I have not yet used `class` in my code, so – dunno. I guess this is right decision, but looking at code in [`make-error`](https://github.com/JsCommunity/make-error/blob/master/index.js#L41-L72) it could have some bumps. 

@julien-f can you advise – how safe is to `extend` from `Error` class directly?

**Comment by julien-f** [comment]
IMHO, if you want to be compatible with browsers, you should avoid extend `Error` for now.

**Comment by sindresorhus** [comment]
@julien-f Why?

**Comment by julien-f** [comment]
I don't know the ratio of browsers which correctly support inheriting from `Error`.

**Comment by sindresorhus** [comment]
Yeah, I don't know either. Just assumed it would be ok since we already target Node.js 4 JS features.

We can do it sometime in the future though: https://github.com/sindresorhus/got/issues/190

**Pull request closed without merging**
