### PR TITLE
Only throw ParseError on 2xx responses

### LINKED ISSUE #278: Handling both ParseError and HTTPError simultaneously
[Previous discussion](https://github.com/SamVerschueren/travis-got/pull/2#pullrequestreview-25498565) /cc @SamVerschueren @floatdrop @sindresorhus

To summarize, Travis CI’s API returns HTML on `403 Forbidden` responses. For example, try:

```sh
curl -i -H "Authorization: token fail" https://api.travis-ci.org/repos/SamVerschueren/travis-got 
```

When using got’s `json` option this causes a `ParseError` (instead of an `HTTPError`) to be thrown. To avoid this, I suggested to catch the error, check the status code for `403`, and re-throw an `HTTPError`. While this works, it requires us to manually create an error which is an undocumented API of got, as far as I can tell.

@SamVerschueren suggested to disable got’s `json` option and parse the body ourselves. Again, while this works, we would still have to manually throw a `ParseError` in case the body can’t be parsed.

So, either way, we would have to to manually create and throw a `ParseError` or an `HTTPError`.

> I would recommend looking into how other HTTP libs handle this, like `request`. We might be doing something wrong, or not.

@sindresorhus request currently just [logs a debug message](https://github.com/request/request/blob/v2.80.1/request.js#L1116-L1120). This behavior has also been discussed in https://github.com/request/request/issues/440.

### PR DESCRIPTION
**Pull request by sonicdoe**
Resolves #278.

### CODE REVIEW

**Comment by floatdrop** [comment]
We should add a note about parsing error policy, I guess.

**Comment by sindresorhus** [comment]
@sonicdoe Can you add a note in the readme about the behavior?

**Comment by sonicdoe** [comment]
Of course, done.

**Comment by sindresorhus** [comment]
Thank you! :)

**Pull request merged**
