### PR TITLE
Remove the `host` header on redirect

### LINKED ISSUE #1240: redirecting request has wrong host
#### Describe the bug

 - Node.js version:  10.19.0
 - OS & version: debian

#### Actual behavior
headers with wrong host when `host` defined in options.headers

#### Expected behavior
request with right host header for redirecting uri

#### Code to reproduce

```js
nock('https://testweb.com').get('/redirect').reply(302, undefined, {location: 'https://webtest.com/'});
nock('https://webtest.com').get('/').reply(function (_uri, _body) {
    return [200, this.req.getHeader('host')];
});

const resp = await got('https://testweb.com', {headers: {host: 'wrongsite.com'}});
console.log(resp.body);
```
output:  `wrongsite.com`

https://github.com/sindresorhus/got/blob/812deb690bc67b9bb2a0a28f10ece46c7905c78c/source/core/index.ts#L1053-L1066

when redirect host different with origin request, the host of headers is not removed, so when next request, the host header will be replaced, that caused an wrong request

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

### PR DESCRIPTION
**Pull request by MittWillson**
#### Checklist

- [x] I have read the documentation.
- [ ] I have included a pull request description of my changes.
- [x] I have included some tests.
- [ ] If it's a new feature, I have included documentation updates.

Fixes #1240

### CODE REVIEW

**Comment by szmarczak** [comment]
This is missing a test

**Comment by MittWillson** [comment]
@satazor I tested it again, i was wrong, this is not a issue, sorry

**Comment by MittWillson** [comment]
> This is missing a test

Hi, i debugged agian for reason, and i found why,  `host` in options.headers replaced the finnal reuqest, is this a bug or feature?

**Comment by szmarczak** [comment]
This is definitely a bug. Nice one! I'll look into this tomorrow, it's quite late here.

**Comment by MittWillson** [comment]
@szmarczak sure, and glad to hear that :)

**Comment by szmarczak** [comment]
Nice one, thanks! :raised_hands:

**Pull request merged**
