### PR TITLE
fix redirects for host/port etc... in options

### PR DESCRIPTION
**Pull request by floatdrop**
Accidentally pushed #55 in master.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> got('host.com', { host: 'newhost.com' }).pipe(process.stdout);

Can't we just throw on this? I see no sane reason why this should be supported. What even is the expected outcome if it were allowed?

**Comment by floatdrop** [comment]
> Can't we just throw on this? I see no sane reason why this should be supported. What even is the expected outcome if it were allowed?

@sindresorhus I guess we can. Also we can:

 * drop this feature and don't do `objectAssign` at all. All 'bad' properties would be just ignored.
 * drop those properties on redirect (this will allow `got(conf.host, {path: '/mypath'})`)

As you say - `there is no sane reason to do so`, so probably there is no sane way to deal with it.

**Comment by sindresorhus** [comment]
Sounds good :+1:

**Comment by floatdrop** [comment]
@sindresorhus which one?

**Comment by sindresorhus** [comment]
2

**Pull request merged**
