### PR TITLE
Ignore invalid cookies if sent by web server

### PR DESCRIPTION
**Pull request by iczero**
Some web servers (*cough* incapsula *cough*) will send invalid cookies. These should not fail the request, and instead should be ignored.

#### Checklist

- [x] I have read the documentation.
- [x] I have included a pull request description of my changes.
- [ ] I have included some tests. - probably not needed?
- [ ] If it's a new feature, I have included documentation updates.

### CODE REVIEW

**Comment by iczero** [comment]
There exists a test for checking whether or not got throws on invalid cookies. I believe invalid cookies should be silently ignored, or at least there should exist a configuration for that.

**Comment by sindresorhus** [comment]
I don't think we should silently ignore invalid cookies.

@szmarczak Do you think it's worth having an option for this?

**Comment by szmarczak** [comment]
I don't think so. If we were willing to support deprecated functionalities, our code would be bloated.

**Comment by iczero** [comment]
Currently, if the server sends invalid cookies, the entire request fails. As such, it would be impossible to use this module to perform requests to any server that sends invalid cookies. It's not so much about "supporting deprecated functionalities" as it is simply preserving compatibility. Currently, the invalid cookie in question fails the validation done by tough-cookie, however Chrome stores it fine.

**Comment by sindresorhus** [comment]
Browsers are much more lenient than a request library should be. Got strives to be strict and not silently handle invalid data. However, I realize the real world is not perfect, so I'm ok with adding an option for this. Should be named `ignoreInvalidCookies` and should be opt-in, documented, and tested.

**Pull request closed without merging**
