### PR TITLE
Got 12 improvements

### LINKED ISSUE #1538: Enhance pagination with parsed Link header
#### What problem are you trying to solve?

Paginating some GitHub API endpoints with extra logic (logging etc) when reaching internal limit of fetched pages.

#### Describe the feature

Would be nice to have more control on pagination logic. For example, [parse-link-header](https://github.com/thlorenz/parse-link-header) provides well structured format of parsed Link header.

**Raw Link header:**
```
<https://<api_url>?page=3&per_page=100>; rel="next",
<https://<api_url>?page=1&per_page=100>; rel="prev"; pet="cat",
<https://<api_url>?page=5&per_page=100>; rel="last"
```
**Parsed result:**
```javascript
{
  next: {
    page: '3',
    per_page: '100',
    rel: 'next',
    url: '<api_url>?page=3&per_page=100',
  },
  prev: {
    page: '1',
    per_page: '100',
    rel: 'prev',
    pet: 'cat',
    url: '<api_url>?page=1&per_page=100',
  },
  last: {
    page: '5',
    per_page: '100',
    rel: 'last',
    url: '<api_url>?page=5&per_page=100',
  },
}
```

If this data will be accessible, for example from [pagination.shouldContinue](https://github.com/sindresorhus/got#paginationshouldcontinue), it will help to add custom logic based on next or previous pages.

**Example**

```javascript
const got = require('got');
const limit = 10;

got.paginate('https://example.com/items', {
  searchParams: {
    limit,
  },
  pagination: {
    shouldContinue: (item, allItems, currentItems, pagination) => {
      if (pagination.next.page > limit) {
        log.warn('Reached page limit');
        return false;
      }
      return true;
    },
  },
});
```

#### Checklist

- [ ] I have read the documentation and made sure this feature doesn't already exist.

### LINKED ISSUE #1663: default maxRetryAfter is not calculated correctly
#### Describe the bug

 - Node.js version: v12.20.0
 - OS & version: macOS Mojave | 10.14.6

In got documentation sais

> If `maxRetryAfter` is set to `undefined`, it will use `options.timeout`.

But is not working well in case of use extends

#### Actual behavior

Event if we use a timeout config like `timeout: { request: 5000 }`if don't provide a `maxRetryAfter` value when  config is "normalized" the maxRetryAfter is being calculated as `Infinity`

#### Expected behavior

As per documentation `maxRetryAfter` should get `5000` as value.

#### Code to reproduce

```js
const { describe, it } = require('mocha')
const { strictEqual } = require('assert').strict
const Got = require('got')

describe.only('default maxRetryAfter', function () {
  it('should get timeout value', async function () {
    const newGot = Got.extend({ timeout: { request: 5000 } })
    strictEqual(newGot.defaults.options.retry.maxRetryAfter, 5000)
  })
})

/**
      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

Infinity !== 5000

/*
```

I think the problem is because the code to calculate default value for `maxRetryAfter` is in the method  `normalizeArguments()` and is calculating the default value before the options are merged, for this reason get timeout as undefined and the `maxRetryAfter` is getting infinity value

### LINKED ISSUE #1668: Merging `port` into defaults doesn't work with `prefixUrl`
#### Describe the bug

With Node 12, got@11.8.2.

Merging `port` into default options doesn't work when `prefixUrl` is set.

#### Code to reproduce

See https://github.com/jmm/repro-got-merge-port-to-defaults.

```js
const gotInstance = got.extend({
  mutableDefaults: true,
  prefixUrl: "http://example.com",
})

const port = 1234

gotInstance.defaults.options = gotInstance.mergeOptions(gotInstance.defaults.options, {
  port,
})

assert.equal(gotInstance.defaults.options.port, port)
```

#### Actual behavior

I expect port to be set as specified and the assertion to be true.

#### Expected behavior

Port is undefined.

---

I suspect this code: https://github.com/sindresorhus/got/blob/v11.8.2/source/core/index.ts#L1639-L1645

### PR DESCRIPTION
**Pull request by szmarczak**
This is a redo of #1521

Fixes #1668 (tested)
Fixes #1663 (tested)
Fixes #1538 (tested)

**If this gets merged, we need to open an issue to fix the docs. I'll do them, as well as migration notes etc.**

<strike>
**Note**: By using the `Options` class we introduce a regression! In some cases where option normalization throws `error.options` is `undefined`. ~~This could be solved via **not throwing in the `Options` constructor**, but setting a property e.g. `lastKnownError` instead. That way `error.options` would be defined. It's just a matter what we do consider more friendly.~~ Ok found a better way - let's define `error.options` on the error thrown by the `Options` constructor. Later!
</strike>
<br>
<br>

- [x] Improved option normalization (new class: `Options`)
  - [x] `new Options(url | options, options?, defaults?)`
    **Note**: Only the first `url` instance is used.
  Meaning: `got('https://a', {url: 'https://b'})` will actually make a request to `a`.
  If you expect to replace the `url` option, then you need pass the initial `url` like this:
  `got({url: 'https://a', ...otherOptions})`
  - [x] `options.merge(newOptions)` replaced `got.mergeOptions` & `Request.normalizeArguments`
    **Note**: It does NOT merge the `url` option - but it **does** merge the `searchParameters` option
  - [x] Throws when an option does not exist
  - [x] Dropped legacy URL support, use `options.url` instead (a URL instance)
  - [x] Creates a brand new object for the native `http` options
  - [x] No implicit `timeout` declaration, use `{timeout: {request: 1000}}` instead
  - [x] No implicit `retry` declaration, use `{retry: {limit: 3}}` instead
  - [x] `dnsLookupIpVersion` is now a number (`4` or `6`) or undefined
- [x] Switched to `get-stream` (getting a buffer from a stream)
- [x] Refactored `core/index.ts`
- [x] Refactored `as-promise/index.ts`
  - [x] Moved the `onCancel` handlers out of `makeRequest` in order to prevent them being called multiple times (`.destroy()` needs to be called only once)
  - [x] The `Request` class now provides `rawBody` if `request._noPipe` is `true` (used internally by Promise API)
  - [x] Switched from `for/entries` to classic `for` loop when iterating over `afterResponse` hooks in order to improve performance
        **Why**: `.entries()` sends a query to get enumerable properties + generates an array - but we don't need that since we already know the enumerable properties since it's an array and we don't need to generate a new one
  - [x] [Fixed `Request` options not being reused on retry](https://github.com/sindresorhus/got/blob/c3ca847318327152aba6e0eb3bde4b34d7cc3d5e/source/as-promise/index.ts#L137-L139) (~~needs a test~~ tested)
- [x] Moved `Response`-related stuff to `core/response.ts`
- [x] Moved error definitions to `core/errors.ts` - you now have to import them directly, meaning you cannot access them via `got.RequestError`
- [x] New error type: `RetryError` which always triggers a new retry when thrown
- [x] Moved `waitForOpenFile` to `core/utils/wait-for-open-file.ts`
- [x] Added missing `once` types for Stream API
- [x] Switched from symbols to `private`s
- [x] `redirectUrls` and `requestUrl` now give URL instances
- [x] The retry timeout in `request._beforeError` is now promisified
- [x] Renamed `request.aborted` to `request.isAborted`
- [x] Renamed the `lookup` option to `dnsLookup`
- [x] The `beforeRetry` hook now accepts only one argument: `error`
      To retrieve:
        - the underlying request: `error.request`
        - the underlying options: `error.options`
        - current attempt number: `error.request.retryCount + 1`
- [x] The `beforeRedirect` hook's first argument (`options`) is now a cloned instance of the Request options.
     This was done to make retrieving the original options possible. To retrieve the original options, use `plainResponse.request.options`.
- [x] The `redirect` event now takes two arguments: `updatedOptions` and `plainResponse`
- [x] ~~The `retry` event now takes only one argument: `error`~~ (reverted; reason: the current API is much nicer)
      ~~To get the attempt count, use `error.request.retryCount + 1`~~
- [x] The `socketPath` option has been removed. Use the `unix:` protocol instead.
- [x] The `retryWithMergedOptions` function no longer returns a `Promise`. Keep in mind that this should be the last function being executed in an `afterResponse` hook.
- [x] `error.options` is now enumerable
- [x] `defaults.handlers` don't need a default handler (`(options, next) => next(options)`) now.
- [x] Renamed `options.https` to `options.httpsOptions` 
- [x] Removed internal `_isAboutToError` function
- [x] Renamed the `searchParams` option to `searchParameters`
- [x] You can no longer set `options.agent` to `false`. To do so, you need to define all the `options.agent` properties: `http`, `https` and `http2`.
- [x] Refactored Got interface (instances, defaults, etc.)
- [x] The `init` hook now accepts a second argument: `self`, which points to an `Options` instance
- [x] The `init` hooks are ran only when passing an options object explicitly. It's no longer called on `got('https://example.com')` - in order to trigger `init` hooks, you need to call `got('https://example.com', {})`
- [x] When passing a `url` option when paginating, it now needs to be an absolute URL - the `prefixUrl` option is always reset from now on. The same when retrying in an `afterResponse` hook.
- [x] Fixed tests
  - [x] Fix `test/arguments.ts`
  - [x] Fix `test/create.ts`
  - [x] Fix `test/normalize-arguments.ts`
  - [x] Fix `test/hooks.ts`
- [x] `got.extend(...)` will throw when passing some options that don't accept `undefined` - `undefined` no longer retains the old value, as setting `undefined` explicitly may reset the option
- [x] Look at the code and update what's changed
- [ ] Created a new documentation

#### To be fixed

- [ ] #1654
- [ ] #1591 & #1462
- [ ] #1610 (might be already fixed - needs a test)
- [ ] #1137
- [ ] #1599
- [ ] #1574 - needs a test
- [ ] #1569
- [ ] #1553
- [ ] #1567 (might be already fixed - needs a test)
- [ ] #1527
- [ ] #1450 - needs a test
- [ ] #1503
- [ ] #1507
- [ ] #1492
- [ ] #1408
- [ ] #1117 (maybe, may be postponed to Got 12.x / 13)
- [ ] #1405 (docs)

#### Checklist

- [ ] I have read the documentation.
- [x] I have included a pull request description of my changes.
- [x] I have included some tests.
- [ ] If it's a new feature, I have included documentation updates in both the README and the types.

### CODE REVIEW

**Comment by szmarczak** [comment]
So I've benchmarked option normalization... and it's great <3 130k/s when normalizing URL. But when just cloning the options... 1M/s. Blazing fast.

**Comment by szmarczak** [comment]
`asPromise` scores ~3600 req/s. That's 1200 req/s slower than `core` (Stream API). I don't think we can do faster.

@Nytelife26 If you have any idea on how to improve `asPromise/index.ts`, feel free to chime in. Note we don't want to lose any of the available features Got has to offer.

**Comment by Nytelife26** [comment]
> If you have any idea on how to improve asPromise/index.ts

I apologise, I have only just seen this. Do you still require assistance? If so, I will be available tonight @szmarczak

**Comment by szmarczak** [comment]
> Do you still require assistance?

No, I don't require, I'm just kindly asking if you have spare time to have a quick peek ;) If that's not the case, no problem, we'll manage. I ran [a flamegraph](https://github.com/davidmarkclements/0x) and the bottleneck here comes from the native `http` module (well, streams too). I highly doubt we can improve the performance of `asPromise`.

**Comment by Nytelife26** [comment]
> to have a quick peek

Yes, that's absolutely fine. I'll take a look in an hour or so when I get home.

> I highly doubt we can improve the performance of `asPromise`

I'm sure we can. Who knows until we try? We got this :)

**Comment by erfanium** [comment]
May this PR fix this https://github.com/sindresorhus/got/pull/1549#issuecomment-740883268? It bothers me.

**Comment by szmarczak** [comment]
@erfanium https://github.com/sindresorhus/got/pull/1549#issuecomment-740891030

**Comment by szmarczak** [comment]
IOW yes

**Comment by szmarczak** [comment]
Todo: do not override properties that already exist when assigning promise properties to async handler result.

**Comment by szmarczak** [comment]
All tests are passing. >90% coverage.

**Comment by szmarczak** [comment]
Meh, failing on Node.js 12.

**Comment by szmarczak** [comment]
`cache` is failing because of #1385. Prepare for a stupid workaround.

**Comment by szmarczak** [comment]
Oh, and one major thing: this PR uses TS default export.

**Comment by sindresorhus** [comment]
> Fixes #1668 (needs a test)
Fixes #1663 (needs a test)
Fixes #1538 (needs a test)

Did tests get added for these?

**Comment by szmarczak** [comment]
Not yet, I can get them added in an hour. Currently I'm finishing my PR in `ava/typescript`.

**Comment by szmarczak** [comment]
Added the tests :)

**Comment by sindresorhus** [comment]
> Created a new documentation

Can you open an issue for this?

**Comment by sindresorhus** [comment]
This is looking really good! Super nice work as always. 🙌

**Comment by sindresorhus** [comment]
> Renamed the searchParams option to searchParameters

I don't think we should do this though. Can you revert that? While I generally prefer full words, I think it's more important here to use the same name as `Fetch`, and also, it's not worth doing a breaking change just for that.

**Comment by szmarczak** [comment]
Sure, will do this in a few hours.

**Comment by szmarczak** [comment]
7b3cbfdf4d7e5264c3acba7576b4e25f082c8f97

**Pull request merged**
