### PR TITLE
Do not import package.json

### LINKED ISSUE #891: Fix building Got
Currently, when publishing, the package only ends up containing a `dist/package.json` file...

However, running `npm build` normally at least puts the correct files in `dist/source`, although that's incorrect too, they should be in `dist`.

### PR DESCRIPTION
**Pull request by szmarczak**
Fixes #891

### CODE REVIEW

**Comment by sindresorhus** [comment]
You need to remove it in the test too.

**Comment by szmarczak** [comment]
Yeah, trying to fix this and that...

**Comment by szmarczak** [comment]
Is it possible to test publishing somehow? E.g. using Travis?

**Comment by sindresorhus** [comment]
Not sure. Something more useful would be a TS lint rule to prevent importing package.json.

**Pull request merged**
