### PR TITLE
Use AVA's TypeScript support

### PR DESCRIPTION
**Pull request by novemberborn**
Not sure what to do about this line:

https://github.com/sindresorhus/got/blob/689c660441569faad4bf6a98dd75cbd187a78185/tsconfig.json#L9

### CODE REVIEW

**Comment by szmarczak** [comment]
I'll look at this tomorrow (looks awesome btw). I'm not at home atm, I've got a flight in a few hours.

**Comment by szmarczak** [comment]
You can remove `typeRoots`, it has no impact in this case :)

**Comment by szmarczak** [comment]
Wow, the time went down from 5m 20s to 2m 20s, great job! :rocket:

**Comment by szmarczak** [comment]
Umm... The coverage is broken: https://coveralls.io/builds/28353742/source?filename=dist/source/as-stream.js

**Comment by novemberborn** [comment]
nyc reports coverage in the CI run: https://travis-ci.org/sindresorhus/got/jobs/642036302?utm_medium=notification&utm_source=github_status

Weirdly enough with the `.js` extensions. But this is probably something you can tweak in the nyc config.

Coveralls shows the coverage numbers, but can't find the file sources: https://coveralls.io/builds/28353742

**Pull request merged**
