### PR TITLE
Add documentation on how to test requests

### LINKED ISSUE #454: How to mock "got"?
I'm wondering if there is an easy way to mock "got" dependency?
I managed to deal with it using `proxyquire` but looking for easier solution.

### PR DESCRIPTION
**Pull request by kevva**
Fixes #454.

### CODE REVIEW

**Comment by lukechilds** [comment]
Do you think it would be worth mentioning [`create-test-server`](https://github.com/lukechilds/create-test-server) here?

The official Got tests will actually be using this once #387 is merged?

**Comment by kevva** [comment]
> Do you think it would be worth mentioning create-test-server here?

Might be. I think their use cases are a little different. E.g. I would use `nock` for mocking real API requests while I would use `create-test-server` in other cases where I'd just need a server.

**Comment by sindresorhus** [comment]
I think it's worth mentioning it. Nock should be good enough for most REST cases, but sometimes you need real integration tests, and that's when `create-test-server` becomes useful.

**Comment by sindresorhus** [comment]
@lukechilds LGTY?

**Comment by lukechilds** [comment]
Yeah, perfect 👌

**Comment by sindresorhus** [comment]
Thanks Kevin 👌✨

**Pull request merged**
