### PR TITLE
Fixed `options.port` on redirect

### LINKED ISSUE #1437: Doesn't override port on redirect
#### Describe the bug

 - Node.js version: 12.16.2
 - OS & version: Linux 4.15.0-112-generic #113~16.04.1-Ubuntu SMP Fri Jul 10 04:37:08 UTC 2020 x86_64  GNU/Linux

When request URL is defined by individual components in options (i.e. `protocol`, `hostname`, `port`, `pathname`), `hostname` and `port` (and perhaps the `protocol`) remain original on redirect.

#### Actual behavior

After a redirect, `got` performs a new request at URL that consists of the `pathname` from the `Location:` header and `hostname` from request `options`.

#### Expected behavior

After a redirect, `got` should perform a new request at the URL present in the `Location:` header.

#### Code to reproduce

```js
const express = require('express');
const got = require('got');
const url = require('url');

const app1 = express();
const app2 = express();

const SERVER1PORT = 12345;
const SERVER2PORT = 54321;

app1.get(
  '/redirect',
  (req, res) => res.redirect(`http://127.0.0.1:${SERVER2PORT}/get?param=value`)
);

app1.get('/get', (req, res) => res.send('Host 1'));
app2.get('/get', (req, res) => res.send('Host 2'));

const requestUrl = {
  protocol: 'http:',
  hostname: '127.0.0.1',
  port: 12345,
  pathname: '/redirect'
};

const server1 = app1.listen(SERVER1PORT).on('listening', () => {
  const server2 = app2.listen(SERVER2PORT).on('listening', async () => {
    const responseOne = await got(requestUrl);
    console.log(responseOne.body);
  
    const responseTwo = await got(url.format(requestUrl));
    console.log(responseTwo.body);
  
    const responseThree = await got({url: url.format(requestUrl)});
    console.log(responseThree.body);

    server1.close();
    server2.close();
  });
});
```

Actual output:
```
Host 1
Host 2
Host 2
```

Expected output:
```
Host 2
Host 2
Host 2
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

### PR DESCRIPTION
**Pull request by Giotino**
#### Checklist

- [x] I have read the documentation.
- [x] I have included a pull request description of my changes.
- [x] I have included some tests.
- [x] If it's a new feature, I have included documentation updates in both the README and the types.

Fixes #1437

### CODE REVIEW

**Comment by szmarczak** [comment]
Thanks a lot! 🙌

**Comment by sindresorhus** [comment]
@Giotino Would you be interested in joining Got as a maintainer? You've done a lot of good PRs. 🙌🏻

**Comment by Giotino** [comment]
Sure, it would be a pleasure to work with you to improve this repo.

**Comment by sindresorhus** [comment]
@Giotino Awesome. Welcome to the team!

We usually do pull requests for most changes as it's always good to get a second eye on changes.

**Pull request merged**
