### PR TITLE
Documentation for Got 12

### LINKED ISSUE #1405: Document `stream.options`
#### What would you like to discuss?

I would like to log the request body/json when an error occurs because it makes it easy to reproduce the failed request. I know that I can log the response body with `err.response.body`, but can't find a way to do so with the request body.

How can I log the body of the request?

#### Checklist

- [x] I have read the documentation.

### PR DESCRIPTION
**Pull request by szmarczak**
https://github.com/sindresorhus/got/tree/docs-v12#documentation

Fixes #1405

TODO (the below will be another PR):
- update TypeScript docs
- Node.js migration guide
- Axios migration guide

#### Checklist

- [x] I have read the documentation.
- [x] I have included a pull request description of my changes.
- [ ] I have included some tests.
- [ ] If it's a new feature, I have included documentation updates in both the README and the types.

### CODE REVIEW

**Comment by sindresorhus** [comment]
I think we should preserve the initial usage example in the readme, so users can quickly see how easy Got is: https://github.com/sindresorhus/got#usage (JSON and Promise examples)

**Comment by sindresorhus** [comment]
There's as a lot of empty files.

**Comment by szmarczak** [comment]
> There's as a lot of empty files.

Yes, currently I'm busy with uni stuff. I'll try to finsih this next week.

**Comment by szmarczak** [comment]
Random tests failing:
- https://github.com/sindresorhus/got/runs/3037357629#step:5:615
- https://github.com/sindresorhus/got/runs/3037317576#step:5:615
- https://github.com/sindresorhus/got/runs/3037302713#step:5:620

They shouldn't fail. I guess GitHub Actions is busy and sometimes a single request can take [more than 400ms](https://github.com/sindresorhus/got/blob/main/test/retry.ts#L597). Travis CI flashbacks...

**Comment by sindresorhus** [comment]
@szmarczak Are you done with the docs? If so, I think it's easier to just merge it in and then I can do a look over and fix typos and stuff. It's faster for me to just fix things directly than to comment on things here.

**Comment by sindresorhus** [comment]
> TODO (the below will be another PR):

Can you open an issue so we don't forget?

**Comment by szmarczak** [comment]
> Are you done with the docs?

Yes.

> Can you open an issue so we don't forget?

Sure.

**Comment by szmarczak** [comment]
https://github.com/sindresorhus/got/issues/1684#issuecomment-879022015

**Pull request merged**
